# Funding options for CTOrendang

# GitHub Sponsors
github: [HunterHo07]

# Other platforms (uncomment and add if applicable)
# patreon: your-patreon
# open_collective: your-collective
# ko_fi: your-kofi
# custom: ['https://ctorendang.com/support']

