name: ctorendang
description: AI-powered marketplace to find experienced CTOs for your startup
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.0
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0

  # Navigation
  go_router: ^13.0.0

  # Network
  dio: ^5.4.0
  retrofit: ^4.0.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Authentication
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.0
  sign_in_with_apple: ^5.0.0
  local_auth: ^2.1.8

  # Payments
  flutter_stripe: ^10.1.0

  # Messaging
  firebase_messaging: ^14.7.0
  socket_io_client: ^2.0.3
  flutter_local_notifications: ^16.3.0

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^3.0.0
  flutter_spinkit: ^5.2.0
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.0.1

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1

  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0

  # Date & Time
  timeago: ^3.6.0
  flutter_datetime_picker_plus: ^2.1.0

  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/screenshots/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

